<div class="navbar-brand-box">
    <!-- Dark Logo-->
    <a href="index.html" class="logo logo-dark">
        <span class="logo-sm">
            <img src="assets/images/logo.png" alt="" style="border:1px solid #fff; border-radius:58px;" height="38">&nbsp;&nbsp;<span style="color:#fff; font-size:22px; padding-bottom:10px; font-weight:bold;">E-PROTECH</span>&nbsp;&nbsp;
        </span>
        <span class="logo-lg">
            <img src="assets/images/logo.png" alt="" style="border:1px solid #fff; border-radius:58px;" height="38">&nbsp;&nbsp;<span style="color:#fff; font-size:22px; padding-bottom:10px; font-weight:bold;">E-PROTECH</span>&nbsp;&nbsp;
        </span>
    </a>
    <!-- Light Logo-->
    <a href="index.html" class="logo logo-light">
        <span class="logo-sm">
            <img src="assets/images/logo.png" alt="" style="border:1px solid #fff; border-radius:58px;" height="38">&nbsp;&nbsp;<span style="color:#fff; font-size:22px; padding-bottom:10px; font-weight:bold;">E-PROTECH</span>&nbsp;&nbsp;
        </span>
        <span class="logo-lg">
            <img src="assets/images/logo.png" alt="" style="border:1px solid #fff; border-radius:58px;" height="32">&nbsp;&nbsp;<span style="color:#fff; font-size:18px; padding-bottom:10px; font-weight:bold;">E-PROTECH</span>&nbsp;&nbsp;
        </span>
    </a>
    <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
        <i class="ri-record-circle-line"></i>
    </button>
</div>