<div class="container-fluid">

    <div id="two-column-menu">
    </div>
    <ul class="navbar-nav" id="navbar-nav">
        <li class="menu-title"><span data-key="t-menu">Menu</span></li>
        <li class="nav-item">
            <a class="nav-link menu-link" href="index.php" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarDashboards">
                <i class="ri-dashboard-2-line"></i> <span data-key="t-dashboards">Dashboards</span>
            </a>
        </li> <!-- end Dashboard Menu -->

        <li class="menu-title"><i class="ri-more-fill"></i> <span data-key="t-pages">Pages</span></li>

        <li class="nav-item">
            <a class="nav-link menu-link" href="suppliers.php" role="button">
                <i class="ri-node-tree"></i> <span data-key="t-authentication">Suppliers</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link menu-link" href="users.php" role="button">
                <i class="ri-folder-line"></i> <span data-key="t-authentication">Sections</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link menu-link" href="suppliers.php" role="button">
                <i class="ri-folders-line"></i> <span data-key="t-authentication">Categories</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link menu-link" href="users.php" role="button">
                <i class="ri-user-line"></i> <span data-key="t-authentication">Users</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link menu-link" href="user-groups.php" role="button">
                <i class="ri-shield-user-line"></i> <span data-key="t-authentication">User Groups</span>
            </a>
        </li>

    </ul>
</div>